### ISSUE TITLE
Report API Usage and/reduce Usage

### ISSUE THREAD

**Issue by AngellusMortis** [newrelic-experimental/gha-new-relic-exporter#15]
One of our repos common hits the [primary rate limit for the GITHUB_TOKEN.](https://docs.github.com/en/rest/overview/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-github_token-in-github-actions) We are trying to optimize the API calls to reduce this happening, but that can be very difficult. 

Would it be possible to add a counter and report how many API calls are being used by the action? And/or attempt to reduce the amount of API calls that are being made? 

The data I am able to get shows the action (may) scale the API usage based on the size of workflow being ingested, so larger workflows will use more API requests. The my estimates for the workflows usage vary anywhere from 3 requests up to 384 per run, but those are just estimates since I am reporting the rate limit before and after it runs, which does not take into another other jobs running at the same time.

Just for reference, 100 API calls for _this_ action means it can only run 150 times/hour (enterprise, non-enterprise limit is 10/hr) _excluding_ the API calls for the workflow run itself that is being ingested.

We have considered moving all of the requests for this action to a new auth token, like another PAT, but that is really just a bandaid, not a long term solution to scaling problem of the API usage.

**Comment by dpacheconr** [comment]
I don't expect that many API calls, unless I am missing something.
If you enable debugging as per https://github.com/newrelic-experimental/gha-new-relic-exporter#troubleshooting, look at the debug messages for urllib3 which I believe is the underlying library used by [ghapi](https://ghapi.fast.ai/cli.html#ghapi) I can only see 4 per each run when I ran on my test environment.
Obviously I don't have complex environment like yours, so if you could run it on yours with debug mode on and let us know the outcome that would be great

**Comment by AngellusMortis** [comment]
Yep, it looks like it is consistently only 4 requests no matter the size of the workflow. The new way to enable troubleshooting helps a ton with understanding what the workflow is doing. Thanks!
