### ISSUE TITLE
Feature Request: Log level reporting to New Relic

### ISSUE THREAD

**Issue by AngellusMortis** [newrelic-experimental/gha-new-relic-exporter#16]
So we want to actually start better tracking CI failures and _why_ a step failed. It would help a lot with the queries if the `severity.text` level reported to New Relic matched [the log level](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-debug-message) for the line. 

![firefox_MXaEOyRfQZ](https://github.com/newrelic-experimental/gha-new-relic-exporter/assets/490848/d31ce6f7-4387-427f-b7b8-b5971c129d1c)

Just from a quick search through our logs:

* All warning log lines start with `##[warning]`
* All error log lines start with `##[error]`
* All error log lines start with `##[notice]`

I am guessing similarly debug levels would show up as `##[debug]` but we are actually doing debug level messages differently since they require `ACTIONS_STEP_DEBUG` to be able enabled to show up (we wrap them in a group instead so they are hidden by default, but still there in case the job fails).

**Comment by dpacheconr** [comment]
this is now available on latest release
