### ISSUE TITLE
Self hosted pipeline

### ISSUE THREAD

**Issue by yagobatista** [newrelic-experimental/gha-new-relic-exporter#18]
I have two action one is self-hosted and the other not.
The hosted by github the logs work fine and apear on new relic.
On the self-hosted one only the traces go to new relic .

I assuming the problem is because the action is self-hosted, but does any one have any ideas on what may be happening?

If you need any additional detail I'm happy to provide it

![image](https://github.com/newrelic-experimental/gha-new-relic-exporter/assets/20402021/f562acbf-d85f-41f0-877f-49e50dc46f95)

**Comment by dpacheconr** [comment]
To obtain logs the action tries to connect to this endpoint https://github.com/newrelic-experimental/gha-new-relic-exporter/blob/main/src/exporter.py#L92

If you enable GHA_DEBUG and run again, you should see some errors in logs that may help in your investigation

Feel free to post the debug logs here so we can have a look as well in case you can't find the issue yourself
