### ISSUE TITLE
Custom docker image source

### ISSUE THREAD

**Issue by Mallear** [newrelic-experimental/gha-new-relic-exporter#20]
Hello,

I want to use this action inside a big mono repo with a lot workflow running.
As I am running self hosted running, I would like to cache/reuse the Docker image instead of re-building it for each run. 
Is there a way to specify a Docker image ?

Thanks

**Comment by dpacheconr** [comment]
Have you tried referencing it as docker container instead?
https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#referencing-a-container-on-docker-hub
The image details https://github.com/newrelic-experimental/gha-new-relic-exporter/pkgs/container/gha-new-relic-exporter

**Comment by dpacheconr** [comment]
you managed to get it working?
