### ISSUE TITLE
jobs completed but having error code: StatusCode.PERMISSION_DENIED

### ISSUE THREAD

**Issue by butchcarpio** [newrelic-experimental/gha-new-relic-exporter#8]
##[debug]Evaluating condition for step: 'new-relic-exporter'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: new-relic-exporter
##[debug]Loading inputs
##[debug]Loading env
Run org-private/gha-newrelic-exporter@v2
/usr/local/bin/docker run --name e22609cb30[1](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:1)686d14[2](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:2)2dae67486e6758efa4_516aab --label 60e226 --workdir /github/workspace --rm -e "GHA_TOKEN" -e "NEW_RELIC_LICENSE_KEY" -e "GHA_RUN_ID" -e "GHA_RUN_NAME" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_EVENT_PATH" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "GITHUB_ACTION" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "RUNNER_DEBUG" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/runner/_work/_temp/_github_home":"/github/home" -v "/runner/_work/_temp/_github_workflow":"/github/workflow" -v "/runner/_work/_temp/_runner_file_commands":"/github/file_commands" -v "/runner/_work/basic-apps/basic-apps":"/github/workspace" 60e226:09cb[3](https://github.com/basic-apps/basic-apps/actions/runs/6427124231/job/17452532592#step:6:3)01686d1[4](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:4)22dae67486e67[5](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:5)8efa4
Log file does not exist: analyze / CodeQL Analysis/1_Set up job.txt
Log file does not exist: analyze / CodeQL Analysis/2_Set up runner.txt
Log file does not exist: analyze / CodeQL Analysis/3_Checkout repository.txt
Log file does not exist: analyze / CodeQL Analysis/4_Set up Node.js.txt
Log file does not exist: analyze / CodeQL Analysis/5_Set up JDK.txt
Log file does not exist: analyze / CodeQL Analysis/[6](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:6)_Set up .NET.txt
Log file does not exist: analyze / CodeQL Analysis/[7](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:7)_Set up Go.txt
Log file does not exist: analyze / CodeQL Analysis/[8](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:8)_Set up Maven.txt
Log file does not exist: analyze / CodeQL Analysis/[9](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:9)_Host memory usage.txt
Log file does not exist: analyze / CodeQL Analysis/10_Configure CodeQL.txt
Log file does not exist: analyze / CodeQL Analysis/11_Initialize CodeQL.txt
Log file does not exist: analyze / CodeQL Analysis/12_Autobuild.txt
Log file does not exist: analyze / CodeQL Analysis/13_Perform CodeQL analysis.txt
Log file does not exist: analyze / CodeQL Analysis/22_Post Perform CodeQL analysis.txt
Log file does not exist: analyze / CodeQL Analysis/23_Post Initialize CodeQL.txt
Log file does not exist: analyze / CodeQL Analysis/24_Post Set up JDK.txt
Log file does not exist: analyze / CodeQL Analysis/25_Post Checkout repository.txt
Log file does not exist: analyze / CodeQL Analysis/26_Complete runner.txt
Log file does not exist: analyze / CodeQL Analysis/27_Complete job.txt
All data exported to New Relic
Failed to export traces to otlp.nr-data.net:43[18](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:19), error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4[31](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:32)8, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:[43](https://github.com/org-private/basic-app/actions/runs/6427124231/job/17452532592#step:6:44)18, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
Failed to export traces to otlp.nr-data.net:4318, error code: StatusCode.PERMISSION_DENIED
##[debug]Docker Action run completed with exit code 0
##[debug]Finishing: new-relic-exporter

**Comment by dpacheconr** [comment]
Have you double checked the New Relic API key you using is ingest license not user license

**Comment by butchcarpio** [comment]
Fantastic, updating it to ingest key solves the permission denied. however, may i ask about this one `Log file does not exist: analyze / CodeQL Analysis/27_Complete job.txt` ? is there an option that this log file can be created via the github settings?

**Comment by dpacheconr** [comment]
that path is automatically generated based on your job/step names, can you share you workflow.yaml configuration, I can then have a look and try see if there is anything wrong with exporter file name generation

**Comment by butchcarpio** [comment]
here is the codeql workflow. it is a reusable workflow.
`name: CodeQL

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      paths-ignore:
        required: false
        type: string        
      queries:
        required: false
        type: string
      node-version:
        required: false
        type: string
        default: 18
      java-version:
        required: false
        type: string
        default: 11
      maven-version:
        required: false
        type: string
        default: '3.8.7'
      dotnet-version:
        required: false
        type: string
        default: 7
      go-version:
        required: false
        type: string
        default: '^1.19.0'
      setup-android:
        required: false
        type: boolean
        default: false
      runner: 
        required: false
        default: common-8gb
        type: string
      store-sarif:
        required: false
        type: boolean
        default: false
      working-directory:
        required: false
        type: string                

jobs:
  analyze:
    name: Analyze
    runs-on: ${{ inputs.runner }}
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      DOTNET_INSTALL_DIR: '~/.dotnet'
      CODEQL_ENABLE_EXPERIMENTAL_FEATURES_SWIFT: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      if: inputs.language == 'javascript' && inputs.node-version != ''
      with:
        node-version: ${{ inputs.node-version }}

    - name: Set up JDK
      uses: actions/setup-java@v3
      if: inputs.language == 'java' && inputs.java-version != ''
      with:
        java-version: ${{ inputs.java-version }}
        distribution: temurin

    - name: Set up Maven
      if: inputs.language == 'java' && inputs.maven-version != ''
      run: |
        wget -q https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${{ inputs.maven-version }}/apache-maven-${{ inputs.maven-version }}-bin.tar.gz
        tar xzvf apache-maven-${{ inputs.maven-version }}-bin.tar.gz
        echo "$GITHUB_WORKSPACE/apache-maven-${{ inputs.maven-version }}/bin" >> $GITHUB_PATH
      shell: bash

    - name: Set up Android SDK 
      uses: android-actions/setup-android@v2
      if: inputs.language == 'java' && inputs.setup-android == true

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      if: inputs.language == 'csharp' && inputs.dotnet-version != ''
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Set up Go
      uses: actions/setup-go@v3
      if: inputs.language == 'go' && inputs.go-version != ''
      with:
        go-version: ${{ inputs.go-version }}

    - name: Host memory usage
      if: runner.os == 'Linux'
      run: free

    - name: Configure CodeQL
      id: config
      uses: asurion-private/codeql-config-action@v1
      with:
        paths-ignore: ${{ inputs.paths-ignore }}      
        queries: ${{ inputs.queries }}

    - name: Calculate CodeQL RAM
      if: runner.os == 'Linux'
      env: 
        RUNNER: ${{ inputs.runner }}
      run: |
        if [[ "$RUNNER" == "common-8gb" ]]; then
          echo "Setting CodeQL RAM to 5632 MB"
          echo "CODEQL_RAM_CUSTOM=5632" >> "$GITHUB_ENV"
        elif [[ "$RUNNER" == "common-16gb" ]]; then
          echo "Setting CodeQL RAM to 11059 MB"
          echo "CODEQL_RAM_CUSTOM=11059" >> "$GITHUB_ENV"        
        elif [[ "$RUNNER" == *"-8g"* ]]; then
          echo "Setting CodeQL RAM to 6144 MB"
          echo "CODEQL_RAM_CUSTOM=6144" >> "$GITHUB_ENV"
        elif [[ "$RUNNER" == *"-16g"* ]]; then
          echo "Setting CodeQL RAM to 13312 MB"
          echo "CODEQL_RAM_CUSTOM=13312" >> "$GITHUB_ENV"        
        fi

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ inputs.language }}
        config-file: ${{ steps.config.outputs.config-file }}
        ram: ${{ env.CODEQL_RAM_CUSTOM }}
        setup-python-dependencies: false        

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Perform CodeQL analysis
      id: codeql-analysis    
      uses: github/codeql-action/analyze@v2
      with:
        category: '/language:${{ inputs.language }}'

    - name: Store CodeQL results as artifact
      uses: actions/upload-artifact@v3
      if: inputs.store-sarif == true && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
      with: 
          name: codeql-sarif-${{ inputs.language }}
          path: ${{ steps.codeql-analysis.outputs.sarif-output }}
          retention-days: 30`

**Comment by butchcarpio** [comment]
though we can see on the workflow output that log file does not exist, i can see metrics on the distributed tracing. is this the expected data metrics that we put in NR?
![image](https://github.com/newrelic-experimental/gha-new-relic-exporter/assets/91664381/054df38d-3a93-4f70-a6f0-43780a7da5f4)

**Comment by dpacheconr** [comment]
this is expected, the logs are used for some status updates and errors inbox and logs in context

**Comment by butchcarpio** [comment]
alright. so for now, the only missing was the logs?

**Comment by dpacheconr** [comment]
from your screenshots, yes looks like it.
I plan on reviewing this at some point this week

**Comment by dpacheconr** [comment]
I just tried and can't replicate the issue
can you show me your new-relic-exporter workflow?

Does it look like the below?

name: new-relic-exporter

on:
  workflow_run:
    workflows: ['*']
    types: [completed] # defaults to run on every completed workflow run event

env:
  GHA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  GHA_RUN_ID: ${{ github.event.workflow_run.id }}
  GHA_RUN_NAME: ${{ github.event.workflow_run.name }}

jobs:
  new-relic-exporter:
    name: new-relic-exporter
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: new-relic-exporter
        uses: newrelic-experimental/gha-new-relic-exporter@latest

**Comment by dpacheconr** [comment]
Is this working for you now?

**Comment by dpacheconr** [comment]
no reply for over 3 weeks, closing this issue, please re-open if issue persists
